name: Java Selenium Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.0'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Selenium Tests
        run: ./gradlew test --info # Adiciona mais detalhes nos logs
